#!/usr/bin/env python3
"""Build a review-friendly Markdown stub for a single command.

Reads the per-version text files produced by fetch_and_parse_pdfs.py
(build/pdf_text/SIM800_AT_V*.txt) and produces docs/ai_review_<cmd>.md
containing side-by-side raw excerpts, ready to be handed to a reviewer
(or an AI) to fill in version_specific / version_reviews.

This script never writes to data/*.yaml.
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_TEXT_DIR = os.path.join(ROOT, "build", "pdf_text")
DOCS_DIR = os.path.join(ROOT, "docs")

MANUALS = [
    ("V1.01", "SIM800_AT_V1.01.txt"),
    ("V1.10", "SIM800_AT_V1.10.txt"),
    ("V1.12", "SIM800_AT_V1.12.txt"),
]
RESPONSE_RE = re.compile(r"(Max(?:imum)?\s+Response\s+Time|Response\s+Time)", re.I)

def page_slices(text):
    """Yield (page_number, page_text) tuples from a dumped file."""
    cur = None
    buf = []
    for line in text.splitlines():
        m = re.match(r"^----- PAGE (\d+) -----$", line)
        if m:
            if cur is not None:
                yield cur, "\n".join(buf)
            cur = int(m.group(1))
            buf = []
        else:
            buf.append(line)
    if cur is not None:
        yield cur, "\n".join(buf)

def find_hits(text, command):
    needle = command.upper()
    hits = []
    for pno, body in page_slices(text):
        if needle in body.upper():
            hits.append((pno, body))
    return hits

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cmd", required=True, help="AT command, e.g. AT+CSQ")
    args = ap.parse_args()
    cmd = args.cmd.upper()

    lines = [f"# AI Review Stub: `{cmd}`", ""]
    lines.append("Generated by `scripts/ai_version_diff.py`. "
                 "Hand this file to a reviewer/AI to produce real "
                 "`version_specific` and `version_reviews` entries.")
    lines.append("")

    any_hit = False
    for ver, fname in MANUALS:
        path = os.path.join(PDF_TEXT_DIR, fname)
        if not os.path.exists(path):
            lines.append(f"## {ver} — MISSING ({fname} not in build/pdf_text/)")
            lines.append("")
            continue
        with open(path, encoding="utf-8") as f:
            text = f.read()
        hits = find_hits(text, cmd)
        lines.append(f"## {ver} — {len(hits)} hit(s) on pages "
                     f"{[h[0] for h in hits]}")
        lines.append("")
        if not hits:
            lines.append("_No page contains the command string._")
            lines.append("")
            continue
        any_hit = True
        for pno, body in hits:
            lines.append(f"### {ver} page {pno}")
            lines.append("")
            lines.append("```")
            # Trim to keep the stub reviewable
            snippet = body if len(body) <= 4000 else body[:4000] + "\n...[truncated]"
            lines.append(snippet)
            lines.append("```")
            lines.append("")

    os.makedirs(DOCS_DIR, exist_ok=True)
    out = os.path.join(DOCS_DIR, f"ai_review_{cmd.replace('+','_')}.md")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    if not any_hit:
        print(f"[warn] no hits for {cmd} in any manual; stub still written")
    print(f"[stub] {cmd} -> {os.path.relpath(out, ROOT)}")

if __name__ == "__main__":
    main()