#!/usr/bin/env python3
"""Cross-check version coverage and identify gaps.

Reads data/*.yaml and produces docs/gaps.md summarising:
  * entries whose `version_specific` is empty even though the command is
    listed as available in more than one version (missing version-level data);
  * entries with no `version_reviews` at all (unreviewed);
  * categories that are declared in category_mapping.yaml but carry no entries.

This is a reporting tool; it never edits the data files.
"""
import os
import sys

try:
    import yaml
except ImportError:
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
DOCS_DIR = os.path.join(ROOT, "docs")
SKIP_FILES = {
    "versions.yaml","chapter_mapping.yaml","category_mapping.yaml",
    "command_inventory.yaml","module_compatibility.yaml"
}

def load_yaml(p):
    with open(p, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}

def main():
    versions_path = os.path.join(DATA_DIR, "versions.yaml")
    vd = load_yaml(versions_path)
    versions = [v["id"] for v in vd["versions"]]

    missing_vspec = []
    unreviewed    = []
    empty_cats    = []

    files = []
    for fname in sorted(os.listdir(DATA_DIR)):
        if not fname.endswith(".yaml") or fname in SKIP_FILES:
            continue
        files.append((fname, load_yaml(os.path.join(DATA_DIR, fname))))

    for fname, data in files:
        ents = data.get("entries", []) or []
        if not ents:
            empty_cats.append(fname)
        for e in ents:
            cmd = e.get("command", "?")
            avail = e.get("available_in_versions") or []
            vspec = e.get("version_specific") or []
            reviews = e.get("version_reviews") or []
            if len(avail) > 1 and not vspec:
                missing_vspec.append((fname, cmd, list(avail)))
            if not reviews:
                unreviewed.append((fname, cmd))

    lines = ["# Gaps Report", ""]
    lines.append("Generated by `scripts/cross_check_versions.py`. "
                 "Lists known gaps that still need human review.")
    lines.append("")

    lines.append("## Commands with empty `version_specific` "
                 "(available in >1 version)")
    lines.append("")
    if missing_vspec:
        lines.append("| file | command | available_in_versions |")
        lines.append("|------|---------|-----------------------|")
        for fname, cmd, avail in missing_vspec:
            lines.append(f"| {fname} | {cmd} | {', '.join(avail)} |")
    else:
        lines.append("(none)")
    lines.append("")

    lines.append("## Commands without any `version_reviews`")
    lines.append("")
    if unreviewed:
        lines.append("| file | command |")
        lines.append("|------|---------|")
        for fname, cmd in unreviewed:
            lines.append(f"| {fname} | {cmd} |")
    else:
        lines.append("(none)")
    lines.append("")

    lines.append("## Data files with no entries")
    lines.append("")
    if empty_cats:
        for fname in empty_cats:
            lines.append(f"- `{fname}`")
    else:
        lines.append("(none)")
    lines.append("")

    lines.append("## Versions tracked")
    lines.append("")
    for v in versions:
        lines.append(f"- {v}")
    lines.append("")

    os.makedirs(DOCS_DIR, exist_ok=True)
    out_path = os.path.join(DOCS_DIR, "gaps.md")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[gaps] wrote {os.path.relpath(out_path, ROOT)} "
          f"({len(missing_vspec)} missing_vspec, "
          f"{len(unreviewed)} unreviewed, "
          f"{len(empty_cats)} empty_files)")

if __name__ == "__main__":
    main()